### ISSUE TITLE
https://github.com/0xAwali/Virtual-Host/releases/tag/nuclei-2.5.3-dev

### ISSUE THREAD

**Issue by meljith-lab** [0xAwali/Virtual-Host#3]
_Originally posted by @0xAwali in https://github.com/0xAwali/Virtual-Host/issues/2#issuecomment-1014930254_

It's only the templates you have provided in  source code ,i have the templates but I don't have nuclei tool which 2.53 with developer version,i need the whole tool

Sorry for trouble please help me

**Comment by 0xAwali** [comment]
you can download it from here https://github.com/0xAwali/Virtual-Host/releases/download/nuclei-2.5.3-dev/nuclei
